#!/usr/bin/env python3
"""Make the banners of the portable machines out of the console chart the issue points at.

Source: https://i.pinimg.com/736x/c4/39/8d/c4398d8910a6f97fd6b997440e0b2c5c.jpg - the chart of
every Game Boy, Game Boy Color and Game Boy Advance colour the selector draws its list with. It is
not stored in the repository; what is stored is the header this script writes.

The chart is the one the issue (#468) names: the first picture of the *GAME BOY* row for the DMG,
the sixth of the *GAME BOY COLOR* row (the yellow one) for the CGB, and the eighth of the *GAME BOY
ADVANCE* block (the indigo one) for the GBA. The devices sit on a white studio background, so the
background is keyed out the way `make_gba_icon.py` does it for the console icon: a texel that is
white (or nearly white) becomes transparent, which leaves a soft edge instead of a jagged one.

Each device then goes into the 96x32 banner the game selector draws DVD banners in (see
`banner.h`), scaled to fit and centered, with the pixels kept as straight R, G, B, A bytes - the
form `BannerRgba` and the selector's `selector_banner_build_rgba` want.

Usage (needs Pillow, which WSL's python3 has):

    python3 src/res/make_portable_banners.py <the downloaded chart.jpg>

The script writes `src/res/portable_banners.h`, which is committed, and nothing else.
"""

import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, "portable_banners.h")

# The banner the selector draws a picture in (see DVD_BANNER_WIDTH / DVD_BANNER_HEIGHT).
BANNER_WIDTH = 96
BANNER_HEIGHT = 32

# The window inside the banner the device is scaled into: the banner's size with a hairline of
# margin, so that a console that is exactly the height of the banner does not touch its edges.
FIT = (BANNER_WIDTH - 2, BANNER_HEIGHT - 2)

# The device of each machine in the chart, as (left, top, right, bottom). See the module comment
# for how they were picked.
DEVICES = (
    ("Dmg", "Game Boy (DMG)", (108, 80, 176, 191)),
    ("Cgb", "Game Boy Color (CGB)", (348, 622, 407, 723)),
    ("Gba", "Game Boy Advance (GBA)", (157, 1105, 265, 1172)),
)


def key_out_white(image):
    """Return the image with the white studio background removed (a soft luminance key)."""
    image = image.convert("RGBA")
    pixels = image.load()
    width, height = image.size

    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            luminance = max(r, g, b)

            if luminance < 235:
                continue                    # the console (and its light grey parts) stays opaque

            # Fade the near-white pixels out, so the silhouette keeps a soft edge instead of a
            # jagged one.
            fade = (luminance - 235) / 20.0
            pixels[x, y] = (r, g, b, int(a * (1.0 - min(1.0, fade))))

    return image


def trimmed(image):
    """Drop the fully transparent border the key left behind."""
    box = image.getbbox()
    return image.crop(box) if box else image


def banner(image):
    """Scale the device to fit the banner and center it there."""
    image = image.copy()
    image.thumbnail(FIT, Image.LANCZOS)

    canvas = Image.new("RGBA", (BANNER_WIDTH, BANNER_HEIGHT), (0, 0, 0, 0))
    canvas.paste(image, ((BANNER_WIDTH - image.width) // 2, (BANNER_HEIGHT - image.height) // 2))
    return canvas


def emit_array(stream, name, image):
    """Write the pixels of one banner as the R, G, B, A bytes of every texel."""
    pixels = list(image.tobytes())

    stream.write("static const uint8_t PortableBanner%s[PortableBannerWidth * PortableBannerHeight * 4] =\n{\n" % name)

    for y in range(BANNER_HEIGHT):
        row = pixels[y * BANNER_WIDTH * 4:(y + 1) * BANNER_WIDTH * 4]
        stream.write("\t" + ", ".join("0x%02x" % b for b in row) + ",\n")

    stream.write("};\n\n")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2

    chart = Image.open(sys.argv[1])

    if chart.size != (736, 2134):
        print("the chart is %sx%s, not the 736x2134 the crops were taken from" % chart.size)
        return 1

    banners = []

    for name, title, crop in DEVICES:
        device = trimmed(key_out_white(chart.crop(crop)))
        banners.append((name, title, banner(device)))
        print("%s: %s -> %s" % (name, title, banners[-1][2].size))

    with open(HEADER, "w") as stream:
        stream.write("// Generated by make_portable_banners.py from the console chart the game selector's\n")
        stream.write("// portable machines are drawn from (see the script for the source and the crops).\n")
        stream.write("// The banners are PortableBannerWidth x PortableBannerHeight texels of straight R, G, B, A\n")
        stream.write("// bytes, the form BannerRgba and the selector's own banner builder want.\n\n")
        stream.write("static const int PortableBannerWidth = %i;\n" % BANNER_WIDTH)
        stream.write("static const int PortableBannerHeight = %i;\n\n" % BANNER_HEIGHT)

        for name, title, image in banners:
            emit_array(stream, name, image)

    print("wrote %s" % HEADER)
    return 0


if __name__ == "__main__":
    sys.exit(main())
