//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Dolwin.rc
//
#define ID_POPUP_FILE                   0
#define IDR_MANIFEST                    1
#define IDI_DOLWIN_ICON                 101
#define IDR_ACCELERATOR                 103
#define IDR_MAIN_MENU                   104
#define ID_STATUS_BAR                   105
#define ID_SELECTOR                     106
#define IDI_GCN_ICON                    107
#define IDI_GCN_SMALL_ICON              108
#define IDD_FILE_FILTER                 111
#define IDD_MEMCARD_SETTINGS            115
#define IDD_MEMCARD_CHOOSESIZE          116
#define IDD_FONT_SETTINGS               117
#define IDI_MOREICON1                   118
#define IDI_MOREICON2                   119
#define IDI_MOREICON3                   120
#define IDD_SETTINGS_EMU                123
#define IDD_SETTINGS_GUI                124
#define IDD_SETTINGS_HW                 125
#define IDD_SETTINGS_HLE                126
#define IDI_MOREICON4                   127
#define ID_DEVELOPMENT_SYSINFO          129
#define IDI_MOREICON5                   130
#define IDI_MOREICON6                   131
#define ID_DEVELOPMENT_ASSERTINTERRUPT  132
#define ID_ASSERTINTERRUPT_CPDRAWDONE   133
#define ID_ASSERTINTERRUPT_CPDRAWTOKEN  134
#define ID_Menu                         135
#define ID_ASSERTINTERRUPT_AIDMA        136
#define ID_ASSERTINTERRUPT_AIDSP        137
#define ID_ASSERTINTERRUPT_AISTREAM     138
#define ID_ASSERTINTERRUPT_VIINT        139
#define ID_ASSERTINTERRUPT_DVD          140
#define ID_ASSERTINTERRUPT_SI           141
#define IDD_ABOUT                       143
#define IDB_BITMAP1                     144
#define IDB_BITMAP2                     145
#define IDB_BITMAP3                     146
#define IDB_BITMAP4                     147
#define IDB_BITMAP5                     148
#define IDB_BITMAP6                     149
#define IDB_BITMAP7                     150
#define IDB_BITMAP8                     151
#define IDD_DIALOG_PAD                  152
#define IDC_FILE_FILTER                 1001
#define IDC_DOL_FILTER                  1002
#define IDC_ELF_FILTER                  1003
#define IDC_GCM_FILTER                  1004
#define IDC_GMP_FILTER                  1005
#define IDC_FONT_ANSICOMBO              1012
#define IDC_FONT_SJISCOMBO              1013
#define IDC_MEMCARD_CONNECTED           1014
#define IDC_MEMCARD_SYNCSAVE_FALSE      1015
#define IDC_MEMCARD_SYNCSAVE_TRUE       1016
#define IDC_MEMCARD_CHOOSEFILE          1017
#define IDC_MEMCARD_FILE                1018
#define IDC_MEMCARD_PATH                1019
#define IDC_MEMCARD_NEW                 1020
#define IDC_MEMCARD_SIZES               1021
#define IDC_MEMCARD_SIZEDESC            1022
#define IDC_USEMMX                      1025
#define IDC_CPU_CORE                    1026
#define IDC_SIMULATE_APPLDR             1026
#define IDC_MEMORY_MODE                 1027
#define IDC_MTXHLE                      1027
#define IDC_COUNTER_FACTOR              1028
#define IDC_COUNTER_DELAY               1029
#define IDC_BAILOUT                     1030
#define IDC_CHECK3                      1031
#define IDC_CHECK4                      1032
#define IDC_CHECK5                      1033
#define IDC_CHECK6                      1034
#define IDC_CF_DEFAULT                  1035
#define IDC_DELAY_DEFAULT               1036
#define IDC_BAILOUT_DEFAULT             1037
#define IDC_HLE_MODE                    1038
#define IDC_MMXFLAG                     1038
#define IDC_DSP_FAKE                    1039
#define IDC_SSEFLAG                     1039
#define IDC_KEEP_ARENA                  1040
#define IDC_KILLPATH                    1040
#define IDC_CONSOLE_VER                 1041
#define IDC_BUTTON2                     1041
#define IDC_ADDPATH                     1041
#define IDC_RTC                         1042
#define IDC_FILEFILTER                  1042
#define IDC_ARENA_LO                    1043
#define IDC_GX_POLL                     1043
#define IDC_ARENA_HI                    1044
#define IDC_VI_STRETCH                  1044
#define IDC_CHOOSE_BOOTROM              1045
#define IDC_CHOOSE_DSPDROM              1046
#define IDC_CHOOSE_DSPIROM              1047
#define IDC_WINDALL                     1048
#define IDC_CHECK2                      1049
#define IDC_ENSURE_WINDALL              1049
#define IDC_PATHLIST                    1052
#define IDC_ABOUT_RELEASE               1071
#define IDC_BUTTON_X                    1072
#define IDC_BUTTON_START                1073
#define IDC_BUTTON_Y                    1074
#define IDC_BUTTON_A                    1075
#define IDC_BUTTON_B                    1076
#define IDC_BUTTON_RIGHT                1077
#define IDC_BUTTON_DOWN                 1078
#define IDC_BUTTON_LEFT                 1079
#define IDC_BUTTON_UP                   1080
#define IDC_BUTTON_XDOWN50              1081
#define IDC_BUTTON_XDOWN100             1082
#define IDC_BUTTON_XRIGHT50             1083
#define IDC_BUTTON_XRIGHT100            1084
#define IDC_BUTTON_XUP100               1085
#define IDC_BUTTON_XUP50                1086
#define IDC_BUTTON_XLEFT50              1087
#define IDC_BUTTON_XLEFT100             1088
#define IDC_CHECK_PLUG                  1089
#define IDC_BUTTON_CXUP                 1090
#define IDC_BUTTON_CXLEFT               1091
#define IDC_BUTTON_CXDOWN               1092
#define IDC_BUTTON_CXRIGHT              1093
#define IDC_BUTTON_TRIGGERR             1094
#define IDC_BUTTON_TRIGGERL             1095
#define IDC_PAD_CONFIG_OK               1096
#define IDC_PAD_CONFIG_CANCEL           1097
#define IDC_PAD_CONFIG_CLEAR            1098
#define IDC_PAD_ABOUT_OK                1099
#define IDC_BUTTON_TRIGGERZ             1100
#define IDC_ABOUT_STAMP                 1101
#define IDC_PAD_CONFIG_OK2              1102
#define IDC_PAD_CONFIG_CLEAR2           1103
#define IDC_PAD_CONFIG_DEFAULT          1104
#define IDC_BOOTROM_FILE                1105
#define IDC_DSPDROM_FILE                1106
#define IDC_SYSLINK1                    1106
#define IDC_DSPIROM_FILE                1107
#define ID_FILE_RECENT_1                40003
#define ID_FILE_RECENT_2                40004
#define ID_FILE_RECENT_3                40005
#define ID_FILE_RECENT_4                40006
#define ID_FILE_RECENT_5                40007
#define ID_FILE_IPLMENU                 40010
#define ID_FILE_COVER                   40011
#define ID_FILE_CHANGEDVD               40012
#define ID_FILE_QUICKSAVE               40013
#define ID_FILE_QUICKLOAD               40014
#define ID_FILE_EXIT                    40015
#define ID_OPTIONS_SETTINGS             40016
#define ID_FILE_REFRESH                 40017
#define ID_OPTIONS_VIEW_DISABLE         40018
#define ID_OPTIONS_VIEW_SMALLICONS      40019
#define ID_OPTIONS_VIEW_LARGEICONS      40020
#define ID_OPTIONS_VIEW_SORTBY_1        40021
#define ID_OPTIONS_VIEW_SORTBY_2        40022
#define ID_OPTIONS_VIEW_SORTBY_3        40023
#define ID_OPTIONS_VIEW_SORTBY_4        40024
#define ID_OPTIONS_VIEW_SORTBY_5        40025
#define ID_OPTIONS_ALWAYSONTOP          40026
#define ID_OPTIONS_GRAPHICS             40027
#define ID_OPTIONS_SOUND                40028
#define ID_OPTIONS_INPUT                40029
#define ID_OPTIONS_DVD                  40030
#define ID_OPTIONS_BBA                  40031
#define ID_OPTIONS_NET                  40031
#define ID_OPTIONS_CONTROLLERS_PORT1    40032
#define ID_OPTIONS_CONTROLLERS_PORT2    40033
#define ID_OPTIONS_CONTROLLERS_PORT3    40034
#define ID_OPTIONS_CONTROLLERS_PORT4    40035
#define ID_OPTIONS_MEMCARDS_SLOTA       40036
#define ID_OPTIONS_MEMCARDS_SLOTB       40037
#define ID_OPTIONS_BOOTROMFONT          40038
#define ID_HELP_ABOUT                   40039
#define ID_FILE_LOAD                    40040
#define ID_FILE_UNLOAD                  40041
#define ID_OPTIONS_VIEW_SORTBY_6        40043
#define ID_FILE_INFO                    40045
#define ID_OPTIONS_VIEW_SORTBY_7        40047
#define ID_FILE_RELOAD                  40050
#define ID_OPTIONS_VIEW_FILEFILTER      40051
#define ID_FILE_EDITINFO                40052
#define ID_CPUCOMPARE_SERVE             40053
#define ID_CPUCOMPARE_SERVER            40053
#define ID_CPUCOMPARE_CONNECT1          40054
#define ID_CPUCOMPARE_CONNECT2          40055
#define ID_CPUCOMPARE_CONNECT3          40056
#define ID_CPUCOMPARE_CONNECT4          40057
#define ID_CPUCOMPARE_CONNECT5          40058
#define ID_CPUCOMPARE_DISCONNECT        40059
#define ID_CPUCOMPARE_LIST_SERVERS      40060
#define ID_DEBUG_CONSOLE                40061
#define ID_LOAD_MAP                     40062
#define ID_ADD_MAP                      40063
#define ID_SAVE_MAP                     40064
#define ID_CREATE_MAP                   40065
#define ID_ALLOW_PATCHES                40066
#define ID_LOAD_PATCH                   40067
#define ID_ADD_PATCH                    40068
#define ID_ABOUT_GFX                    40071
#define ID_ABOUT_AUD                    40072
#define ID_ABOUT_PAD                    40073
#define ID_ABOUT_DVD                    40074
#define ID_ABOUT_BBA                    40075
#define ID_ABOUT_NET                    40075
#define ID_HELP_DEVMANUAL               40076
#define ID_HELP_HELPMANUAL              40077
#define ID_HELP_WEBSITE                 40078
#define ID_RUN_ONCE                     40079
#define ID_DEBUG_ADVANCEDMEMORYMODE     40080
#define ID_DEBUG_MMULOOKUP              40081
#define ID_DEBUG_SIMULATEDCACHE         40082
#define ID_DEBUG_SIMULATEGATHERBUFFER   40083
#define ID_CPUCOMPARE_CLIENT            40084
#define ID_DUMP_RAM                     40086
#define ID_DUMP_ARAM                    40087
#define ID_DUMP_LOMEM                   40088
#define ID_DEVELOPMENT_LOGOUTPUT_CPUGEKKO 40089
#define ID_DEVELOPMENT_LOGOUTPUT_DEBUGGERHWOSREPORT 40090
#define ID_DEVELOPMENT_LOGOUTPUT_GXFIFO 40091
#define ID_DEVELOPMENT_LOGOUTPUT_VIDEOVI 40092
#define ID_DEVELOPMENT_LOGOUTPUT_PIPROCESSORINTERFACE 40093
#define ID_DEVELOPMENT_LOGOUTPUT_MIMEMORYINTERFACE 40094
#define ID_DEVELOPMENT_LOGOUTPUT_AXDMAANDSTREAMING 40095
#define ID_DEVELOPMENT_LOGOUTPUT_DIDVDINTERFACE 40096
#define ID_DEVELOPMENT_LOGOUTPUT_SISERIALINTERFACE 40097
#define ID_DEVELOPMENT_LOGOUTPUT_EXIEXPANSIONINTERFACE 40098
#define ID_HELP_ABOUTPLUGINS            40099
#define ID_DEVELOPMENT_MOUNTDOLPHINSDKASDVD 40100
#define ID_DEVELOPMENT_MOUNTSDK         40101
#define ID_DEVELOPMENT_DSPDEBUG         40102
#define ID_DSP_DEBUG                    40103
#define ID_DEVELOPMENT_EVENTLOGMONITOR  40104
#define ID_DEVELOPMENT_SAVEEVENTLOG     40105
#define ID_DEVELOPMENT_SAVE_EVENTLOG    40106
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         40107
#define _APS_NEXT_CONTROL_VALUE         1107
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
