void __fastcall c_CRAND(uint32_t op);
void __fastcall c_CROR(uint32_t op);
void __fastcall c_CRXOR(uint32_t op);
void __fastcall c_CRNAND(uint32_t op);
void __fastcall c_CRNOR(uint32_t op);
void __fastcall c_CREQV(uint32_t op);
void __fastcall c_CRANDC(uint32_t op);
void __fastcall c_CRORC(uint32_t op);
void __fastcall c_MCRF(uint32_t op);
