void __fastcall c_CRAND(u32 op);
void __fastcall c_CROR(u32 op);
void __fastcall c_CRXOR(u32 op);
void __fastcall c_CRNAND(u32 op);
void __fastcall c_CRNOR(u32 op);
void __fastcall c_CREQV(u32 op);
void __fastcall c_CRANDC(u32 op);
void __fastcall c_CRORC(u32 op);
void __fastcall c_MCRF(u32 op);
